### ISSUE TITLE
菜鸟学习node过程的一些编程思路疑问，希望能解答

### ISSUE THREAD

**Issue by SSSANTON** [bailicangdu/node-elm#10]
你好，我之前一直是用c++,c#开发得比较多，c和java也有用。现在正学习node和javascript做web开发，但有一些地方还没搞明白。我看了好几本node的书籍，都没有找到项目复杂度比较高的例程，基本是一个知识点一个模块，没有很健全的模块体系，还是搞不清这种异步编程思想。你这开源项目做得挺大的，应该能给我答疑。

在C#,C++开发时，是可以主类中定义一些完成不同功能的成员，然后主类的方法中操作这些成员执行相应的功能和逻辑，而成员也可以通过事件或返回值的方式把执行结果反馈到主类。但在搞node+express的时候，就不懂怎样让app.js中的对象和子模块的对象进行交互、不同模块之间要动态传数据时是怎样的方式。比如说，我每个请求路由都独立成js文件了，浏览器有请求的时候，我要返回给浏览器的数据是需要从app.js的对象中获取的，那该怎样跨文件传到我的路由.js文件上？

**Comment by bailicangdu** [comment]
其实nodejs并不适合大型项目的开发，所有的请求都在一个线程里，一个人崩，所有人都崩。所以很少有大型的开源项目。至于文件之间的交互，都是require，export，当然es6的import export更好一点

**Comment by SSSANTON** [comment]
这样啊。
现在要做这样的一个东西：浏览器请求图片——HTTP SERVER——TCP SERVER——TCP SOCKET终端返回图片——TCPSERVER——HTTP SERVER——浏览器
就做获取图片列表和下载图片两个路由，node应该能胜任，就是不知道怎么tcp和http之间怎样交互。

**Comment by bailicangdu** [comment]
socket.io 可以将http协议，改为tcp协议，api简单强大

**Comment by SSSANTON** [comment]
在某个路由里实现如下逻辑：
router.post('/', urlencodedParser, function(req, res, next)
{
调用TCP服务器往TCP终端发送命令
获取到TCP终端返回的数据
把数据返回浏览器客户端
}

可以做到吗？

socket.on('data',function(data)
  {
    var str=data.toString();
 }
主要是不会从这个异步事件返回数据到路由上

**Comment by bailicangdu** [comment]
事件是异步的，只需要在执行完I/O之后调用回调就行

**Comment by SSSANTON** [comment]
大神，能不能讲解清楚一点。最好有简单的代码说明~

**Comment by bailicangdu** [comment]
nodejs是单线程的，准确说说js是单线程的，它不会因为 I/O 操作而阻塞，一旦出现异步，就直接略过，放入事件循环同时注册一个回调，然后执行下面的语句，等异步执行完之后，调用回调，这时候nodejs再次处理这个已经处理好的异步。
