### ISSUE TITLE
本地能进后台管理系统页面吗？

### ISSUE THREAD

**Issue by candy1234momo** [bailicangdu/node-elm#101]
本地能进后台管理系统页面吗？

**Comment by bailicangdu** [comment]
可以

**Comment by xinlai3698** [comment]
![image](https://user-images.githubusercontent.com/11987903/43630529-267796d0-9733-11e8-9b31-65779d30c73e.png)
通过什么连接进入：http://localhost:8001 吗？

**Comment by bailicangdu** [comment]
https://github.com/bailicangdu/vue2-manage 可以运行这个项目
