### ISSUE TITLE
关于食品列表的bug问题

### ISSUE THREAD

**Issue by scottjeremy** [bailicangdu/node-elm#11]
在这个网址里：http://cangdu.org/manage/#/foodList

点击了水饺之后，显示正常，但点击鸡翅后，就显示鸡翅了，连之前的水饺也显示为鸡翅了。

我是新手，但感觉拿这个项目的代码来学习是非常好的，感谢分享！

**Comment by bailicangdu** [comment]
缓存问题，服务器重启就好了
