### ISSUE TITLE
node服务器向第三方服务器请求报错ETIMEDOUT

### ISSUE THREAD

**Issue by njking1992** [bailicangdu/node-elm#110]
node服务器向第三方服务器请求报错ETIMEDOUT。
connect ETIMEDOUT。
我以为是fetch模块出错，改用了request模块，也是同样的错误。
请问哪里的问题。我用的是公司内网，有影响么

**Comment by bailicangdu** [comment]
服务器挂了，正在解决中。。

**Comment by layzynice** [comment]
谢谢您

cangdu <notifications@github.com>编写：

**Comment by layzynice** [comment]
你好，node-elm 的接口是不是以后也不能用了呀？
