### ISSUE TITLE
关于跨域设置的问题

### ISSUE THREAD

**Issue by xusongfu** [bailicangdu/node-elm#113]
res.header("Access-Control-Allow-Origin", req.headers.Origin || req.headers.origin || 'https://cangdu.org');

您好，我看跨域这边是这样写的，这样写的意义是什么呢，无论req.heaedrs.Origin或者req.headers.origin是什么都允许跨域，那还有什么必要呢，直接 *  不行吗？但是对所有的origin都允许跨域，是不是也不好。

新手，很困扰，烦请大神有空能帮忙解惑，感谢

**Comment by bailicangdu** [comment]
跨域带cookie时，设置*是无效的，必须明确声明跨域的域名，上面两个Origin是为了解决兼容

**Comment by xusongfu** [comment]
//1.跨域设置
module.exports.setCors = (req, res, next) => {
  if((req.headers.origin && req.headers.origin.indexOf('syxgo.com') !== -1) || 
  (req.headers.Origin && req.headers.Origin.indexOf('syxgo.com') !== -1)){
    res.header("Access-Control-Allow-Origin", '*');
    res.header("Access-Control-Allow-Headers", "Content-Type,Content-Length, Authorization, Accept,X-Requested-With");
    res.header("Access-Control-Allow-Methods", "PUT,POST,GET,DELETE,OPTIONS");
    res.header("X-Powered-By", 'Express 4.x');
    if (req.method == 'OPTIONS') {
      res.sendStatus(200);
    } else {
      next();
    }
  }
  else {
    next()
  }
}
我的设计思路是这样的，因为浏览器不同，可能Origin、也可能origin, 如果存在origin，且origin里面包含syxgo.com的话，就允许跨域请求，其他情况不允许，这样对吗？

**Comment by xusongfu** [comment]
另外一个问题，就是在允许跨域下面还有一个判断，  这个又是什么意思呢？因为公司没有可以请教的人，早就关注你的github了，正好看到你开源了项目，学习一番。。
if(req.method == 'OPTIONS'){
res.send(200)
}

**Comment by bailicangdu** [comment]
OPTIONS 请求可以判断是否支持跨域，用于快速响应

**Comment by bailicangdu** [comment]
如果只限定某个域名，*就可以不用设置了

**Comment by xusongfu** [comment]
谢谢！
