### ISSUE TITLE
如何debug模式启动node-elm后台项目

### ISSUE THREAD

**Issue by tomcatGitHub** [bailicangdu/node-elm#115]
我把node-elm项目拉下来后，点击npm scripts脚本dev是启动项目，我要以debug模式启动，该如何配置。请指教一下，拜托了。

**Comment by 695954085** [comment]
你说的是断点的debug模式吗，vscode可以配置nodejs的断点debug开启程序

**Comment by tomcatGitHub** [comment]
嗯，就是那个意思。我用的开发工具是WebStorm，不是vscode.

**Comment by 695954085** [comment]
webstrom也会有断点调试的设置

**Comment by tomcatGitHub** [comment]
我在网上搜索了一阵子，试了很多方法，都没起效果，你能帮我看看，webstom如何debug启动node-elm?
