### ISSUE TITLE
大神，线上的获取用户位置信息是怎么做到的？

### ISSUE THREAD

**Issue by Apigflying** [bailicangdu/node-elm#117]
在本地跑了一下，localhost:8001/v1/cities/?type=guess返回的结果是上海
而https://elm.cangdu.org/v1/cities?type=guess这个接口获取的是当前所在城市。没想明白。望大神赐教

**Comment by bailicangdu** [comment]
调用百度地图api，判断ip地址

**Comment by bailicangdu** [comment]
本地运行拿不到网络ip，所以写死了上海地址

**Comment by Apigflying** [comment]
线上后台用的是nodejs吗？
