### ISSUE TITLE
本地环境如何进入后台管理页面？

### ISSUE THREAD

**Issue by xinlai3698** [bailicangdu/node-elm#118]
![image](https://user-images.githubusercontent.com/11987903/43630591-49e9428a-9733-11e8-99ed-6b6b8cc06b7c.png)
http://localhost:8001这样进入吗？

**Comment by xinlai3698** [comment]
进去后是前台页面呀？
![image](https://user-images.githubusercontent.com/11987903/43630622-686d6006-9733-11e8-8ad2-5ead95c393bd.png)

**Comment by bailicangdu** [comment]
https://github.com/bailicangdu/vue2-manage 这个页面
