### ISSUE TITLE
你好，后台api服务器如何获得用户真实ip

### ISSUE THREAD

**Issue by John117abc** [bailicangdu/node-elm#121]
![image](https://user-images.githubusercontent.com/27287773/43906586-33d81e88-9c26-11e8-845d-dcc63d9e6a9f.png)
部署到服务器之后只能获得本地ip，是需要nginx进行代理穿透吗

**Comment by bailicangdu** [comment]
检查一下访问逻辑，部署到服务器不应该出现这样到问题

**Comment by John117abc** [comment]
发现了是我nginx没有用 X-Forwarded-For

**Comment by John117abc** [comment]
![image](https://user-images.githubusercontent.com/27287773/43965967-37280b16-9cf3-11e8-80d7-2ec4f5bf6d4c.png)
你好，这个数据库部署的时候好像就不能访问了。
