### ISSUE TITLE
Session失效问题

### ISSUE THREAD

**Issue by John117abc** [bailicangdu/node-elm#122]
![image](https://user-images.githubusercontent.com/27287773/44004575-039cb486-9e97-11e8-90c6-0100fbcff14e.png)
![image](https://user-images.githubusercontent.com/27287773/44004580-15bca0ae-9e97-11e8-81df-b60b572b553a.png)
Session里面的admin没有定义
还有退出的时候Session也没有定义里面的id
![image](https://user-images.githubusercontent.com/27287773/44004595-45e47914-9e97-11e8-8156-de48eb5b41f3.png)
是和这个有关系吗
![image](https://user-images.githubusercontent.com/27287773/44004601-5d16e2ca-9e97-11e8-86ad-901e9d8dee9e.png)

**Comment by bailicangdu** [comment]
用户没登陆前，session都是空

**Comment by bailicangdu** [comment]
不知道你说的是不是这样的现象

**Comment by John117abc** [comment]
不是的，是用户登陆了，有session的
![image](https://user-images.githubusercontent.com/27287773/44150977-c6205f42-a0d3-11e8-94c2-f20f20143d93.png)可是没有admin_id，说admin_id未定义

**Comment by John117abc** [comment]
所以就一直判断session失效

**Comment by John117abc** [comment]
数据库里也是有session的
![image](https://user-images.githubusercontent.com/27287773/44151099-160880f2-a0d4-11e8-8a02-8a45ef41f67a.png)
