### ISSUE TITLE
ni hao 后台为什么运行不正常啊

### ISSUE THREAD

**Issue by avtafly** [bailicangdu/node-elm#126]

**Comment by bailicangdu** [comment]
具体报什么错呢

**Comment by zhaoyinpan2** [comment]
| [34/37] Installing nan@~2.10.0在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
/ [34/37] Installing nan@~2.10.0MSBUILD : error MSB4132: 无法识别工具版本“2.0”。可用的工具版本为 "4.0"。

**Comment by zhaoyinpan2** [comment]
Error in MongoDb connection: MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.
0.1:27017]

**Comment by zhaoyinpan2** [comment]
上面的报错是npm install nan报错，我就安装了新的2.11.0，后面的我运行时候报的错，
