### ISSUE TITLE
你好请问下项目怎么打包？

### ISSUE THREAD

**Issue by iyuchang** [bailicangdu/node-elm#136]

**Comment by bailicangdu** [comment]
后台项目，不需要打包

**Comment by iyuchang** [comment]
不是有很多依赖吗，那怎么放到线上呢？node_modules的东西都要放到线上去吗？初学者不懂请见谅

> 后台项目，不需要打包

不是有很多依赖吗，那怎么放到线上呢？node_modules的东西都要放到线上去吗？初学者不懂请见谅

**Comment by bailicangdu** [comment]
都要放上去

**Comment by iyuchang** [comment]
明白了谢谢
