### ISSUE TITLE
你好，请问下这样的项目是怎么打包的，也没有看见安装的有webpack之类的打包工具

### ISSUE THREAD

**Issue by iyuchang** [bailicangdu/node-elm#137]

**Comment by bailicangdu** [comment]
这是后台项目，不需要大包

**Comment by JakeWoki** [comment]
@bailicangdu 那怎么编译成[vue2-manage](https://github.com/bailicangdu/vue2-manage)的manage目录下的文件的呢？

**Comment by bailicangdu** [comment]
不需要编译。后端项目和前端项目不同，前端需要打包成静态文件，后端不需要

**Comment by JakeWoki** [comment]
@bailicangdu 开发用的是window，服务器是linux的话这样也可以直接放上去？没做过服务端不太懂

**Comment by bailicangdu** [comment]
那就需要做兼容了，至于怎么做，要看报什么错

**Comment by 1146612734** [comment]
@bailicangdu manage目录下的文件不就是打包出来的呢？为啥说不需要打包呢？还有如果不需要打包，那需要把项目中的哪些文件放到线上服务器上去呢？求解答，，

**Comment by bailicangdu** [comment]
manage是前端项目，这个是node后台
