### ISSUE TITLE
为什么一跑起来cpu就卡死了

### ISSUE THREAD

**Issue by huangyanyang** [bailicangdu/node-elm#139]
![image](https://user-images.githubusercontent.com/19208961/47987331-3470b100-e11a-11e8-9e93-c8d9f9d650b3.png)

**Comment by bailicangdu** [comment]
很多人是这样，但是我这是好的呀

**Comment by huangyanyang** [comment]
你是不是写了什么消耗性能的东西_(:з」∠)_

**Comment by bailicangdu** [comment]
哦？老哥可以的 @cookingHero

**Comment by xiangzhisuoxin** [comment]
正解
