### ISSUE TITLE
大神 求助?

### ISSUE THREAD

**Issue by jiagujin** [bailicangdu/node-elm#14]
为什么用vue写的项目 打包后 访问这个http://cangdu.org:8001/admin/info 这个接口 返回的数据是{"status":0,"type":"ERROR_SESSION","message":"获取管理员信息失败"}  在本地访问没什么问题 本地用的是代理，获取数据使用的是axios 我给它配置了默认路径 axios.defaults.baseURL = process.env.NODE_ENV === 'production' ? 'http://cangdu.org:8001' : '/api';

**Comment by bailicangdu** [comment]
ERROR_SESSION  session失效

**Comment by jiagujin** [comment]
不太懂  能不能给个解决思路？
