### ISSUE TITLE
google浏览器出现504，其他浏览器却可以，本地后台npm run dev 前端npm run local后

### ISSUE THREAD

**Issue by sxbo** [bailicangdu/node-elm#171]
![image](https://user-images.githubusercontent.com/22607798/59149509-4caa0500-8a48-11e9-85cd-8a6aa4f6858d.png)

**Comment by sxbo** [comment]
望回复，谢谢

**Comment by sxbo** [comment]
@bailicangdu

**Comment by bailicangdu** [comment]
这是后台服务挂了，检查一下后台

**Comment by sxbo** [comment]
前台换了个端口好了，，具体不知道啥原因

**Comment by liuhangb** [comment]
老哥稳，换了个端口立马就好了

**Comment by hanihanihaani** [comment]
老哥稳，换了个端口立马就好了
