### ISSUE TITLE
首页的路由，写在哪呀？（本人菜鸡）

### ISSUE THREAD

**Issue by yaotaiye** [bailicangdu/node-elm#20]
http://localhost:8001/home  没找到这个路由

**Comment by NinjaJin** [comment]
同问

**Comment by sqfbeijing** [comment]
同问

**Comment by bailicangdu** [comment]
本来前后台分离开发，前台的地址和后台接口地址应该是分开的，这个项目里，因为前台用到history模式。需要后台配置路由地址，所以放在一起。这个路由是前台路由
