### ISSUE TITLE
服务器挂掉了

### ISSUE THREAD

**Issue by 913924908** [bailicangdu/node-elm#203]
不能获取服务器的图片了。。。。

**Comment by bailicangdu** [comment]
好的呀

**Comment by 913924908** [comment]
你这在美国呢。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "cangdu"<notifications@github.com&gt;; 
发送时间: 2020年4月20日(星期一) 下午3:32
收件人: "bailicangdu/node-elm"<node-elm@noreply.github.com&gt;; 
抄送: "913924908"<913924908@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [bailicangdu/node-elm] 服务器挂掉了 (#203)





 
好的呀

**Comment by 913924908** [comment]
什么时候可以用呀。。

**Comment by SpanockLaus** [comment]
服务器忘记缴费了嘛

**Comment by bailicangdu** [comment]
备案出了点问题，https可以正常使用
