### ISSUE TITLE
服务器GG了

### ISSUE THREAD

**Issue by yqxshiki** [bailicangdu/node-elm#211]

**Comment by yqxshiki** [comment]
好了，。接口可以用，但是我有个问题 就是你vue2-manage  这个项目再登录后，cookie 是在哪获得的，我怎么没看到啊

**Comment by bailicangdu** [comment]
cookie的操作都在后端做，可以看一下node-elm这个项目

**Comment by bailicangdu** [comment]
验证登录用的是session，https://github.com/bailicangdu/node-elm/blob/master/middlewares/check.js
