### ISSUE TITLE
获取管理员信息失败

### ISSUE THREAD

**Issue by dongxiongle** [bailicangdu/node-elm#23]
// 获取管理员信息
export const getAdminInfo = () => axios.get('/admin/info')
结果为
{"status":0,"type":"ERROR_SESSION","message":"获取管理员信息失败"}
如何才能得到正确的管理员信息

**Comment by bailicangdu** [comment]
先登录再获取

**Comment by bailicangdu** [comment]
"type":"ERROR_SESSION"

**Comment by dongxiongle** [comment]
我又查了一下，axios默认请求头不带cookie，又设置了Axios.defaults.withCredentials = true。
