### ISSUE TITLE
请求回来的 image_path 怎么查看图片呀

### ISSUE THREAD

**Issue by july0701** [bailicangdu/node-elm#237]
大佬！接口里的image_path: "17972b0a08492118.jpg" 要怎么看图片呀。。。。。。太难了

**Comment by bailicangdu** [comment]
地址前缀为http://elm.cangdu.org/img/，比如 http://elm.cangdu.org/img/17972b0a08492118.jpg

**Comment by july0701** [comment]
抱歉。。还是菜鸟 刚看到邮件感谢 已经解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bailicangdu/node-elm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月25日(星期二) 下午3:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bailicangdu/node-elm] 请求回来的 image_path 怎么查看图片呀 (#237)





 
Closed #237.
