### ISSUE TITLE
接口崩溃！

### ISSUE THREAD

**Issue by xiaocaicai123** [bailicangdu/node-elm#248]
哥们，饿了吗接口崩溃了，没办法获取数据！辛苦你能不能改一下，哈哈！

**Comment by bailicangdu** [comment]
> 哥们，饿了吗接口崩溃了，没办法获取数据！辛苦你能不能改一下，哈哈！

已修复

**Comment by xiaocaicai123** [comment]
感谢，非常感谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bailicangdu/node-elm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月1日(星期三) 中午11:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bailicangdu/node-elm] 接口崩溃！ (#248)





  
哥们，饿了吗接口崩溃了，没办法获取数据！辛苦你能不能改一下，哈哈！
  
已修复
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
