### ISSUE TITLE
接口崩溃问题

### ISSUE THREAD

**Issue by caizheyong** [bailicangdu/node-elm#257]
兄弟接口崩溃了，能不能辛苦一下调一下接口呗！谢谢了！

**Comment by caizheyong** [comment]
兄弟接口崩溃了，能不能辛苦一下调一下接口呗！谢谢了！

**Comment by bailicangdu** [comment]
已修复

**Comment by caizheyong** [comment]
非常感谢！

**Comment by lan-john** [comment]
> 已修复

获取不到数据了
{name: "ERROR_GET_POSITION", message: "获取数据失败"}
message: "获取数据失败"
name: "ERROR_GET_POSITION"
