### ISSUE TITLE
服务器接口崩溃

### ISSUE THREAD

**Issue by caizheyong** [bailicangdu/node-elm#260]
老哥：麻烦您能不能重新启动一下服务器，服务器又崩溃了，非常感谢！

**Comment by caizheyong** [comment]
老哥：麻烦您能不能重新启动一下服务器，服务器又崩溃了，非常感谢

**Comment by longmore** [comment]
张荣谋收到，谢谢！

**Comment by caizheyong** [comment]
老哥：服务器那个弄好了吗？可能比较紧急，所有打扰你了，费心了老哥！

**Comment by bailicangdu** [comment]
已修复

**Comment by caizheyong** [comment]
非常感谢老哥！











河南蓝鸥科技有限公司
研发总监-蔡哲永
座机：0371-85967212-607
手机：13103955005
网址：www.lanou3g.com

***@***.***
地址：河南省郑州市高新区莲花街11号纽科科技园B座1~2层


 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sat, Apr 2, 2022 12:39 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [bailicangdu/node-elm] 服务器接口崩溃 (Issue #260)

&nbsp;



 
已修复

**Comment by caizheyong** [comment]
哥们：服务器又崩溃了哈哈，能不能再调整一下啊？非常感谢！











河南蓝鸥科技有限公司
研发总监-蔡哲永
座机：0371-85967212-607
手机：13103955005
网址：www.lanou3g.com

***@***.***
地址：河南省郑州市高新区莲花街11号纽科科技园B座1~2层


 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sat, Apr 2, 2022 12:39 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [bailicangdu/node-elm] 服务器接口崩溃 (Issue #260)

&nbsp;



 
已修复
