### ISSUE TITLE
服务器崩溃了嘛,好像接口用不了了

### ISSUE THREAD

**Issue by cabbage-qwq** [bailicangdu/node-elm#268]
大佬：好像服务器接口又崩溃了，能帮忙调整一下吗？获取城市定位,根据经纬度详细定位,还有食品分类列表和商铺列表都用不了
了,如果可以的话万分感谢

**Comment by longmore** [comment]
张荣谋收到，谢谢！

**Comment by cabbage-qwq** [comment]
大佬;有时间能修复一下嘛,明天要交期末考查项目,今天蹦了,我哭死。如果可以万分感谢。

**Comment by deepastudy** [comment]
> 张荣谋收到，谢谢！

**Comment by cabbage-qwq** [comment]
大佬有时间修复一下嘛,有点紧急,端午节还跑来打扰你,先说声抱歉,如果今天可以修复的话 万分感谢!!!

**Comment by bailicangdu** [comment]
已修复
