### ISSUE TITLE
版本错误？访问http://localhost:8001/是前台的页面 

### ISSUE THREAD

**Issue by visiontech2900** [bailicangdu/node-elm#27]
版本错误？访问http://localhost:8001/是前台的页面

**Comment by bailicangdu** [comment]
前台页面用做数据展示

**Comment by tcg123** [comment]
@bailicangdu 请问怎么在本地访问管理界面，mongodb环境已经配好

**Comment by 7greenfrog7** [comment]
请问怎么访问后台管理系统。。。运行出来还是前端页面啊

**Comment by ChrisKongdj** [comment]
同问，为什么访问localhost：8001是前台页面？怎样才能访问到后台管理页面？
