### ISSUE TITLE
想请教一下后端的部署问题

### ISSUE THREAD

**Issue by sqfbeijing** [bailicangdu/node-elm#28]
大神，您的好几个仓库我都关注了，您简直是我们的福音，但是本人有点菜，我有几个疑惑想不通，想问一下。

 我看到 您的域名是同一个 [http://cangdu.org](http://cangdu.org),服务器也是同一个（阿里云),在项目很多的情况下，您为每个项目分配不同的端口号或者不同的子文件夹。比如：
 
*  http://cangdu.org/pxq/#/?_k=0yewj5 这是为那个react的项目分配到80端口的pxq路径；
*  http://cangdu.org/manage/#/manage 这是后台管理系统；
*  http://cangdu.org:8001/city/96 这是vue2-elm 的前端项目；
*  http://cangdu.org:8001/v2/signout 这是api接口；
*  http://cangdu.org:8003/dialogue 这是微信

### 疑惑

1. 我自己的理解是，我们用nodejs,每一个端口是一个服务， 每一个端口 服务， 都需要跑一个命令行，比如(node server.js),是这样的吗? 比如上面5个项目， 应该用了3个nodejs服务器。
2. 在8003端口的服务，在后端是否要监听不同的路由,(举个例子)http://cangdu.org:8003/index  http://cangdu.org:8003/center   这两个路由不同，但是后端都要返回同一个index.html 对吗..?
3. 在**8001**端口，既有api请求，也会有vue2-elm的很多的页面路由请求，在同一个服务中监听这多个请求，会不会混淆或者不好管理啊？ 
4.  /pxq/ 和 /manage/ 的两个项目都是80端口的请求，应该是用的同一个server吧？ 想知道后端是如何处理的，也是像 上面的3 中 那样监听不同的路由来返回不同项目的 html吗。。？
比如express的这样：

```
app.use('/manage', manage); // 渲染manage的html给后台管理系统项目
app.use('/pxq', pxq); // 渲染pxq的html给后台管理系统项目


```

**Comment by sqfbeijing** [comment]
这个 issue 他们也有差不多的疑惑 。 [https://github.com/bailicangdu/node-elm/issues/20](https://github.com/bailicangdu/node-elm/issues/20)

**Comment by bailicangdu** [comment]
本来前后台分离开发，前台的地址和后台接口地址应该是分开的，这个项目里，因为前台用到history模式。需要后台配置路由地址，所以放在一起。
