### ISSUE TITLE
获取不到定位城市

### ISSUE THREAD

**Issue by lazybat** [bailicangdu/node-elm#29]
前端项目里的online地址改成我自己的域名:8001来访问的，公网ip映射到内网对应的ip和端口。

我把addressComponent.js里写死的ip去掉了
然后运行后，前端得到ERR_DATA
后端看显示的是局域网ip无法获取位置 

请问这里node-elm应该怎么配置运行才行呢？

**Comment by bailicangdu** [comment]
本地运行的ip是127.0.0.1，这个地址无法定位

**Comment by lazybat** [comment]
输出来看了一下，按照现有方法最终得到的是网关的ip
