### ISSUE TITLE
后台系统运行起来，node进程 cpu使用率75~80%；

### ISSUE THREAD

**Issue by WebHW** [bailicangdu/node-elm#31]
1.后台系统运行起来，node进程 cpu使用率75~80%；
2.数据库连接后，还是没有商品展示。
![image](https://user-images.githubusercontent.com/15048039/27774917-1095481e-5fce-11e7-86c5-f74d3e9fb7ff.png)

**Comment by sunchenguang** [comment]
我测试会占用CPU， 60%-70%，占用内存，2G-3G，而且占用内存会一直增加，直到内存溢出挂掉。 这还是在加了`--max-old-space-size=4096`允许它使用4G内容，否则挂的更快。
是不是代码哪没写好，不可能占用这么多吧，

**Comment by sunchenguang** [comment]
CPU, 内容占用一直增加，直到挂掉，感觉是没有正确的释放内存

**Comment by bailicangdu** [comment]
环境问题吧，在我电脑上运行，cup一直3%左右，内存几百兆。在阿里云1核服务器上三个node程序一起运行，cup长期保持20%。内存不到1G

**Comment by huzw3** [comment]
同样遇到这个问题，CPU占用率极高，并且内存启动时就占用3G并不断增加直到内存溢出

**Comment by sunchenguang** [comment]
估计是windows系统的问题？还有就是`cnpm install`时`node-gyp`有报错，这个搞了很久没弄好。不知道有没有关系。反正没遇到过这种问题，也没查到资料
