### ISSUE TITLE
为什么会出现这个错误，求怎么解决

### ISSUE THREAD

**Issue by xiehaitao0229** [bailicangdu/node-elm#4]
PS C:\Users\XieHaitao\Desktop\node-elm-master> npm run dev

> node-elm@1.0.0 dev C:\Users\XieHaitao\Desktop\node-elm-master
> NODE_ENV=development supervisor --harmony index.js

'NODE_ENV' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ru
" "dev"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! node-elm@1.0.0 dev: `NODE_ENV=development supervisor --harmony index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-elm@1.0.0 dev script 'NODE_ENV=development supervisor --harmony index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-elm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development supervisor --harmony index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-elm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-elm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\XieHaitao\Desktop\node-elm-master\npm-debug.log
PS C:\Users\XieHaitao\Desktop\node-elm-master>

**Comment by zygmcc** [comment]
同文，遇到了同样的问题....

**Comment by leroyz** [comment]
同求，我也遇到了

**Comment by bailicangdu** [comment]
增加了cross-env，兼容windows，重新试一下

**Comment by leroyz** [comment]
'cross-env' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "E:\\office\\soft\\nodejs\\node.exe" "C:\\Users\\Lenovo\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js"
"--userconfig=C:\\Users\\Lenovo\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://registry.npm.taobao.org" "run" "online"
npm ERR! node v7.7.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! node-elm@1.0.0 online: `cross-env NODE_ENV=online supervisor --harmony index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-elm@1.0.0 online script 'cross-env NODE_ENV=online supervisor --harmony index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-elm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=online supervisor --harmony index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-elm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-elm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\office\dev\per\node-elm\npm-debug.log

**Comment by bailicangdu** [comment]
npm install

**Comment by zygmcc** [comment]
感谢支持！

win下面还要装.net 2.0 SDK 唉...

**Comment by bailicangdu** [comment]
客气了，windows系统我也不是很熟，遇到这样的问题也很头疼

**Comment by Skirt46** [comment]
OPEN
