### ISSUE TITLE
看了苍渡的vue项目，又看了你的node项目。个人感觉node项目做的有点low

### ISSUE THREAD

**Issue by flyfox11** [bailicangdu/node-elm#40]
个人建议用，koa+sequelize实现，node接口会更优雅。另外看了一部分node项目目录结构，感觉不太好。。另外还是很佩服作者vue项目的，写得很棒！

**Comment by SteveCruise** [comment]
除了koa2，剩下的选型跟我完全一样，代码很优雅，涨了不少知识，赞
