### ISSUE TITLE
数据库

### ISSUE THREAD

**Issue by Jayanzhou** [bailicangdu/node-elm#42]
请问数据表能提供下吗，谢谢

**Comment by a807460184** [comment]
同求数据表，想看看关于商品表的结构

**Comment by beautifulBoys** [comment]
表结构是以模型的形式存在的。https://github.com/bailicangdu/node-elm/blob/master/models/
商品表结构：https://github.com/bailicangdu/node-elm/blob/master/models/shopping/food.js

**Comment by Jayanzhou** [comment]
thanks:v:

**Comment by IDONKN** [comment]
不懂欸，难道要在mongodb里面手敲一遍？？？？？？？？
