### ISSUE TITLE
cangdu大神这里这里，准备从0开始写这个项目，可以把过程发到segmentfault么？

### ISSUE THREAD

**Issue by dingkeshui** [bailicangdu/node-elm#43]
大神好，我刚开始学习vue，只看了几个视频和代码，对vue一片朦胧，感觉还是做项目来的实在。准备从零开始写大神的这个项目来学习vue。请问我可以把过程发布到segmentfault么？如果可以的话需要注意些什么呢？

**Comment by dingkeshui** [comment]
@bailicangdu

**Comment by hochiminh1988** [comment]
这个项目的确不错，比其他github里面的项目详细多
