### ISSUE TITLE
node 是如何支持 es6 module 的

### ISSUE THREAD

**Issue by ghost** [bailicangdu/node-elm#49]
我在搭建项目时添加的 babel 插件和你的一样，但是用 `supervisor --harmony` 的方式启动的话它不是别 es6 的 module，如果添加 babel 插件，以 `babel-node index` 的方式启动是可以支持的，但是这样每次修改都需要手动启动一次，请问作者是如何实现这两个的兼容的？有什么更好的解决办法吗？

**Comment by liangxinwei** [comment]
同问，我用作者的架构开始写一个新项目，把作者的源码替换成我自己的源码，启动的时候还是提示 不识别 import/export，请问作者是如何实现这两个的兼容的？
