### ISSUE TITLE
为什么后台管理系统登录不上，

### ISSUE THREAD

**Issue by zDream** [bailicangdu/node-elm#65]
http://localhost:8001/是可以访问的，
访问后台地址是http://localhost:8001/manage这个吗，为什么不了？而且我看路由也没找到manage这个地址？

**Comment by bailicangdu** [comment]
后台管理是一个独立的项目，需要到相应的仓库下载运行

**Comment by zDream** [comment]
我下载了,不就是这个node-elm仓库吗,就是运行的这个,

**Comment by bailicangdu** [comment]
https://github.com/bailicangdu/vue2-manage
