### ISSUE TITLE
老哥的项目真的很棒！不过有些地方不是很明白，希望指教一下。

### ISSUE THREAD

**Issue by cky-thinker** [bailicangdu/node-elm#67]
老哥的项目很棒！感觉受益匪浅，不过有些地方不是很明白：
请问models的那些表里的字段有具体的解释吗？
感觉有些字段不是很明白。
像userInfo里的 balance（平衡）是什么意思？还有其他的一些字段
能不能给个注释版，方便理解的，谢谢老哥了~

**Comment by Mrpaker** [comment]
balance是余额的意思吧
