### ISSUE TITLE
formidable读不到files？

### ISSUE THREAD

**Issue by szy0syz** [bailicangdu/node-elm#7]
form.parse(req, async (err, fields, files) => {

此处files读不到数据，我正在调，如果能调好我push。

**Comment by bailicangdu** [comment]
我试过了，没有问题的

**Comment by szy0syz** [comment]
不好意思，是我postman的使用姿势问题。
我拿html写了个form测试就行了

**Comment by bailicangdu** [comment]
我还是非常希望你能在以后给我提push的，提bug的人太多，提push的太少

**Comment by szy0syz** [comment]
@bailicangdu 好的，我将会持续关注和学习。
