### ISSUE TITLE
node debugger 报错

### ISSUE THREAD

**Issue by Rachelyep** [bailicangdu/node-elm#71]
你好，请问为什么我输入node --inspect 查看controller里面的shop.js文件 的时候会报Unexpected token import的错误呢，如何打断点可以看到接口的调用情况？盼回复，谢谢

**Comment by qiaoyuwen** [comment]
node不支持es6的import，现在大多都是用babel转换，调试的话建议自己加日志，遇到错误建议最好能多google一下
