### ISSUE TITLE
node-elm ， vue2-manage和vue2-elm这三个项目是什么关系？

### ISSUE THREAD

**Issue by zDream** [bailicangdu/node-elm#74]
哪个是前台，哪个是后台，还有哪个是单独的，看懵了

**Comment by doing123** [comment]
刚接触vue的项目，同问？

**Comment by Rudy24** [comment]
node-elm--专注后台，比如写接口之类。
vue2-manage--做后台管理页面，管理整个网站的数据（如改价格，删除商品之类）。
vue2-elm---移动端界面。

**Comment by Rudy24** [comment]
@doing123 @zDream
