### ISSUE TITLE
npm run dev运行时，报溢出内存

### ISSUE THREAD

**Issue by hjx5309** [bailicangdu/node-elm#87]
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memo
ry
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewFixedArray
 5: v8::internal::HashTable<v8::internal::SeededNumberDictionary,v8::internal::S
eededNumberDictionaryShape>::SetCapacity
 6: v8::internal::HashTable<v8::internal::SeededNumberDictionary,v8::internal::S
eededNumberDictionaryShape>::SetCapacity
 7: v8::internal::StringTable::LookupString
 8: v8::internal::StringTable::LookupString
 9: v8::internal::ParserBase<v8::internal::Parser>::MarkLoopVariableAsAssigned
10: v8::internal::ParserBase<v8::internal::Parser>::MarkLoopVariableAsAssigned
11: 000003EB828847A1
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! node-elm@1.0.0 dev: `cross-env NODE_ENV=development supervisor --harmon
y index.js`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the node-elm@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

**Comment by fredany** [comment]
请问怎么解决的，我这也内存溢出

**Comment by wubing0324** [comment]
我也内存溢出，请问解决了吗。。。
